// ************************ SETTING UP THE ENVIRONMENT
USE ROLE ACCOUNTADMIN;
CREATE WAREHOUSE IF NOT EXISTS DATALAKE_WH
WITH 
WAREHOUSE_SIZE = 'X-SMALL'
MAX_CLUSTER_COUNT = 20
SCALING_POLICY = 'STANDARD';


// ************************ CREATING LANDING WORKSPACE FOR YAHOO FINANCE DATA
CREATE DATABASE IF NOT EXISTS YFINANCE_DB;
CREATE SCHEMA IF NOT EXISTS IN_NSE WITH MANAGED ACCESS;

-- Storage Integration Creation
CREATE OR REPLACE STORAGE INTEGRATION S3_YFINANCE_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:I am::<340591314596>:role/<add_aws_role>'  -- NOTE: MAKE SURE TO UPDATE THE AWS ROLE ARN OF YOUR AWS TRIAL ACCOUNT
  STORAGE_AWS_EXTERNAL_ID  = 'sf-snowpipe-yfinance-ingestion-id' -- NOTE: IF USED DIFFERENT, MAKE SURE TO UPDATE THE EXTERNAL ID OF YOUR AWS TRIAL ACCOUNT
  STORAGE_ALLOWED_LOCATIONS = ('s3://bucket/dir/'); -- NOTE: MAKE SURE TO UPDATE THE S3 PATH OF YOUR AWS TRIAL ACCOUNT

-- Fetching the STORAGE_AWS_IAM_USER_ARN to update IAM role
DESC INTEGRATION S3_YFINANCE_INT;

-- Validating the storage integration
SELECT
  SYSTEM$VALIDATE_STORAGE_INTEGRATION(
    'S3_YFINANCE_INT',
    's3://bucket/dir/', -- NOTE: MAKE SURE TO UPDATE THE S3 PATH OF YOUR AWS TRIAL ACCOUNT
    'top_50_stocks_<DATE>.csv', 'read'); -- NOTE: MAKE SURE TO UPDATE THE FILE NAME

CREATE STAGE IF NOT EXISTS YFINANCE_STG
  URL = 's3://bucket/dir/' -- NOTE: MAKE SURE TO UPDATE THE S3 PATH OF YOUR AWS TRIAL ACCOUNT
  STORAGE_INTEGRATION = S3_YFINANCE_INT;

LIST @YFINANCE_STG;

// ************************ SETTING UP AUTO INGESTION OF DATA USING SNOWPIPE

-- File format creation
CREATE FILE FORMAT IF NOT EXISTS MY_CSV_FORMAT
TYPE = CSV
PARSE_HEADER = TRUE
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

-- Table creation based on the source csv file schema
CREATE TABLE IF NOT EXISTS FYINANCE_NSE_TB
USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(
        INFER_SCHEMA(
          LOCATION=>'@YFINANCE_STG',
          FILE_FORMAT=>'MY_CSV_FORMAT'
        )
    )
);
-- Enabling Schema evolution 
ALTER TABLE FYINANCE_NSE_TB SET ENABLE_SCHEMA_EVOLUTION = TRUE;

CREATE PIPE YFINANCE_NSE_PIPE
  AUTO_INGEST = TRUE
  AS
    COPY INTO YFINANCE_DB.IN_NSE.FYINANCE_NSE_TB
      FROM @YFINANCE_DB.IN_NSE.YFINANCE_STG
      FILE_FORMAT = MY_CSV_FORMAT
      MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- Getting the notification channel to create a set it up at S3 bucket
DESC PIPE YFINANCE_NSE_PIPE;

-- Triggering Pipeline to load existing data
ALTER PIPE YFINANCE_NSE_PIPE REFRESH;
SELECT SYSTEM$PIPE_STATUS( 'YFINANCE_NSE_PIPE' );

SELECT * FROM FYINANCE_NSE_TB;

// XXXXXXXXXXXXXXXXXXXXXX Landing Setup has been completed successfully XXXXXXXXXXXXXXXXXXXXXX
